### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by fibo** [i-n-g-o/TOI#1]
Where it is possible to add TypeScript code?

**Comment by i-n-g-o** [comment]
hi.
can you make a "TypeScript" folder in the repo and make a PR?
you also could send me some files and i will add them.
(did not have time yet to push the code... hopefully i can manage today)

**Comment by fibo** [comment]
I will do a PR adding TypeScript scaffolding.

Can you talk in person to understand better? I guess there is a JS code that handles binary stuff, need to be ported in TS.

I am at the hack space, or we can meet later, I have a Node.JS T-Shirt.

**Comment by i-n-g-o** [comment]
yes, sure. lets meet in person.
i'm on way way back to naxos hall

**Comment by fibo** [comment]
I would proceed by creating TypeScript classes like TOISocket, TOIClient...

**Comment by fibo** [comment]
Great, I will be at the bar in naxos at 13.

**Comment by i-n-g-o** [comment]
perfect. there is one more talk. maybe im a bit late...

**Comment by i-n-g-o** [comment]
im at naxos bar now
